export default function list() {
  console.log('api~~~');
  const res = {
    code: '0',
    errors: null,
    message: null,
    data: {
      total: '38',
      size: '10',
      pages: '4',
      current: '1',
      records: [
        {
          id: '2',
          createdAt: null,
          updatedAt: '1490318457000',
          loggedAt: '1490318457000',
          departmentId: null,
          email: 'hello@world',
          name: '1',
          password: null,
          status: true,
          roles: [
            {
              id: '1',
              description: '',
              name: '超级管理员',
              identity: '',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '1',
            createdAt: null,
            updatedAt: null,
            name: '超级管理员',
            users: [],
          },
        },
        {
          id: '3',
          createdAt: null,
          updatedAt: null,
          loggedAt: null,
          departmentId: null,
          email: 'hello@world',
          name: '2',
          password: null,
          status: true,
          roles: [
            {
              id: '2',
              description: '',
              name: 'a',
              identity: 'a',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '7',
            createdAt: null,
            updatedAt: null,
            name: 'b',
            users: [],
          },
        },
        {
          id: '4',
          createdAt: null,
          updatedAt: '1492643592000',
          loggedAt: '1492643592000',
          departmentId: null,
          email: 'hello@world',
          name: '3',
          password: null,
          status: true,
          roles: [
            {
              id: '11',
              description: '',
              name: 'b',
              identity: 'b',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '4',
            createdAt: null,
            updatedAt: null,
            name: 'b',
            users: [],
          },
        },
        {
          id: '5',
          createdAt: null,
          updatedAt: '1493166857000',
          loggedAt: '1493166857000',
          departmentId: null,
          email: 'hello@world',
          name: '4',
          password: null,
          status: true,
          roles: [
            {
              id: '10',
              description: '',
              name: 'v',
              identity: 'v',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '4',
            createdAt: null,
            updatedAt: null,
            name: 'v',
            users: [],
          },
        },
        {
          id: '6',
          createdAt: null,
          updatedAt: null,
          loggedAt: null,
          departmentId: null,
          email: 'hello@world',
          name: '5',
          password: null,
          status: true,
          roles: [
            {
              id: '10',
              description: '',
              name: 'g',
              identity: 'g',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '4',
            createdAt: null,
            updatedAt: null,
            name: 'g',
            users: [],
          },
        },
        {
          id: '7',
          createdAt: null,
          updatedAt: '1488395114000',
          loggedAt: '1488395114000',
          departmentId: null,
          email: 'hello@world',
          name: '6',
          password: null,
          status: true,
          roles: [
            {
              id: '14',
              description: '',
              name: 'h',
              identity: 'h',
              status: true,
              createdAt: '1487728401000',
              updatedAt: null,
            },
          ],
          department: {
            id: '3',
            createdAt: null,
            updatedAt: null,
            name: 'h',
            users: [],
          },
        },
        {
          id: '8',
          createdAt: null,
          updatedAt: '1488393620000',
          loggedAt: '1488393620000',
          departmentId: null,
          email: 'hello@world',
          name: '7',
          password: null,
          status: true,
          roles: [
            {
              id: '15',
              description: '',
              name: 'j',
              identity: 'j',
              status: true,
              createdAt: '1487728401000',
              updatedAt: null,
            },
          ],
          department: {
            id: '3',
            createdAt: null,
            updatedAt: null,
            name: 'j',
            users: [],
          },
        },
        {
          id: '9',
          createdAt: null,
          updatedAt: null,
          loggedAt: null,
          departmentId: null,
          email: 'hello@world',
          name: '8',
          password: null,
          status: true,
          roles: [
            {
              id: '8',
              description: '',
              name: 'k',
              identity: 'k',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '6',
            createdAt: null,
            updatedAt: null,
            name: 'k',
            users: [],
          },
        },
        {
          id: '10',
          createdAt: null,
          updatedAt: null,
          loggedAt: null,
          departmentId: null,
          email: 'hello@world',
          name: '9',
          password: null,
          status: true,
          roles: [
            {
              id: '8',
              description: '',
              name: 'l',
              identity: 'l',
              status: true,
              createdAt: '1487728398000',
              updatedAt: null,
            },
          ],
          department: {
            id: '6',
            createdAt: null,
            updatedAt: null,
            name: 'l',
            users: [],
          },
        },
      ],
    },
  };

  return new Promise(resolve => {
    setTimeout(() => {
      return resolve({ body: res });
    }, 2000);
  });
}
